### ISSUE TITLE
logOddsScore in Matrix.h not affecting p-value or score

### ISSUE THREAD

**Issue by YichaoOU** [j-andrews7/pytfmpval#3]
Hello,

I'm changing logOdds functions in Matrix.h, but seems that it didn't affect anything.

```C
        // mat[k][p] = log((mat[k][p] + 0.25) /(sum + 1)) - log (background[k]); 
        mat[k][p] = 0  ; 
        // mat[k][p] = log(mat[k][p]) - log (background[k]); 
```

After changing the score, I re-installed python setup.py install.

It is tested on:

```python
>>> from pytfmpval import tfmp
>>> m = tfmp.create_matrix("MA0045.pfm")
>>> tfmp.score2pval(m, 8.7737)
9.992625564336777e-06
>>> tfmp.pval2score(m, 0.00001)
8.773708000000001
```

Always gave the same result.

**Comment by j-andrews7** [comment]
This is likely because the underlying C code is compiled into an extension via SWIG before the package is built (see `/pytfmpval/pytfmpval_wrap.cxx`). You'd have to re-compile to see the changes come into play.  

I'll be honest, it's been a very long time since I looked at this code, and it wasn't a straightforward process to build in the first place. I am going to archive this repo, as it is what it is at this point. You can try to recompile the extension via [SWIG](http://www.swig.org/tutorial.html) and then re-install the package if you'd like. 

I'm also not sure why you want to make this change as it makes no sense to me, but I'll assume you have a plan in mind.
